import type { Metadata } from "next";
import styles from "@/styles/global.module.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={styles.screenContainer}>
      <body>
        <Script
          strategy="beforeInteractive"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=63224f109e789587a0d204e886f416c5&autoload=false`}
        />
        {children}
      </body>
    </html>
  );
}
