import type { Metadata } from "next";
import styles from "@/styles/global.module.css";

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={styles.screenContainer}>
      <body>{children}</body>
    </html>
  );
}
